In [2]:
# 100 Numpy exercises
import numpy as np
print(np.version.short_version)
print(np.__config__.show())

2.5.1
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.33.112.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5fu_d2xs/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      

c:\Users\Ezi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [ ]:
#Create a null vector of size 10
a = np.zeros(10)
#Create a null vector of size 10 but the fifth value which is 1
a[4] = 1
#Create a vector with values ranging from 10 to 49
b = np.arange(10, 50)
#Reverse a vector (first element becomes last)
b[::-1]
#Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0, 9).reshape(3, 3)
#Find indices of non-zero elements from
c = np.array([1, 2, 0, 0, 4, 0])
[x for x in range(c.size) if c[x] != 0]
#Or
np.nonzero([1,2,0,0,4,0])
#Create a 3x3 identity matrix
np.identity(3, int)
#Create a 3x3x3 array with random values
np.random.randn(3, 3, 3)
#Create a 10x10 array with random values and find the minimum and maximum values
d = np.random.rand(10, 10)
d.max()
d.min()
#Create a random vector of size 30 and find the mean value
f = np.random.randn(30)
f.mean()
#Create a 2d array with 1 on the border and 0 inside
g = np.ones((10,10))
g[1:-1,1:-1] = 0
#Or
g = np.zeros((4, 4), dtype=int)
g[0, 0:] = 1
g[-1, 0:] = 1
g[0:, 0] = 1
g[0:, -1] = 1
#How to add a border (filled with 0's) around an existing array?
h = np.pad(g, (1,), 'constant', constant_values=(0,))
h

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

In [ ]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
j = np.zeros((8, 8), int)
j[1::2, ::2] = 1
j[::2, 1::2]= 1
j

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(100, (6,7,8))
#Create a checkerboard 8x8 matrix using the tile function
np.tile(np.array([[0, 1],[1, 0]]), (4, 4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#Normalize a 5x5 random matrix
k = np.random.random((5, 5))
k = (k - np.mean(k)) / np.std(k)
k

array([[ 0.83209888,  1.56768969,  0.30578641, -1.0644812 ,  1.06725898],
       [-0.28411364,  0.98518449, -1.10805169, -1.10012017,  0.19041912],
       [-1.77716619,  1.37260153,  0.41852955,  0.13823232,  0.88856974],
       [-0.63648664, -1.3321888 , -1.3817114 ,  1.19353149, -0.10131597],
       [-0.52162032, -1.18461178,  1.11383759,  1.0473069 , -0.62917889]])

In [44]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)])
color = np.array((255, 128, 0, 255), dtype=color_dtype)
color['R']

#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
l1 = np.arange(15).reshape(5, 3)
l2 = np.arange(6).reshape(3, 2)
np.matmul(l1, l2)
#Or
l1 @ l2

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [59]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
m = np.arange(2, 10)
m[(m > 3) & (8 > m)] *= -1
m

# Consider an integer vector n, which of these expressions are legal?
n = np.arange(10)
n ** n
2 << n >> 2
n <- n
1j*n
n/2/2
#n<n>n



array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])