In [2]:
# 100 Numpy exercises
import numpy as np
print(np.version.short_version)
print(np.__config__.show())

2.5.1
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.33.112.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5fu_d2xs/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      

c:\Users\Ezi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [90]:
a = np.empty(10)
a.__sizeof__()
a[4] = 1
b = np.arange(10, 50)
b[::-1]
np.arange(0, 9).reshape(3, 3)
c = np.array([1, 2, 0, 0, 4, 0])
[x for x in range(c.size) if c[x] != 0]
np.identity(3, int)
np.random.randn(3, 3, 3)
d = np.random.rand(10, 10)
d.max()
d.min()
f = np.random.randn(30)
f.mean()
g = np.zeros((4, 4), dtype=int)
g[0, 0:] = 1
g[-1, 0:] = 1
g[0:, 0] = 1
g[0:, -1] = 1
h = np.pad(g, (1,), 'constant', constant_values=(0,))
h

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

In [16]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [48]:
j = np.zeros((8, 8), int)
j[1::2, ::2] = 1
j[::2, 1::2]= 1
j

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])